### PR TITLE
feat: first attempt at open source and go. Trying to implement an aut…

### PR DESCRIPTION
**Pull request by hsm2k3**
first attempt at open source and go. Trying to implement an auto-retry for issue #151. I'm not sure where to call the retry function. Looking for some constructive criticism here, thank you.

### CODE REVIEW

**Comment by hsm2k3** [comment]
@schollz when you get a chance to review, the idea I was going for is to call the send function 5 more times and pass in the same values. I'm not familiar enough with the code base yet so Idk if that will actually work. I assume all the data would be in the cli.Context pointer, but my gut tells me that's not the case. Also, I'm not clear on where to call the retry func. I'm looking forward to your reply and please go easy on me I'm still learning, thank you.

**Comment by schollz** [comment]
Cool! Thanks for the PR. Nice work.

One thing though is that this doesn't seem to do as described. If I use `--retry` from a sender and then have a receiver cancel the request, the sender will quit.

**Comment by hsm2k3** [comment]
I didn't know receivers can cancel the request. Is [this](https://github.com/schollz/croc/blob/7f9688c7a11fb84b5e0e981216895cd20769c246/src/croc/croc.go#L832) it?

**Comment by schollz** [comment]
Yes, any receiver can press Ctrl+C and cancel the request. It can happen almost anytime in the code...

**Comment by lukas-mertens** [comment]
@hsm2k3 Thanks for implementing this so far. This sounds like a really good feature, please don't give up ;) I would be really glad to have it

**Pull request closed without merging**
