### PR TITLE
.gitignore support

### PR DESCRIPTION
**Pull request by PThorpe92**
https://github.com/schollz/croc/issues/508
Finally had time to look this over, felt pretty stupid about that last PR.  It turns out I was way over-complicating it in some ways and completely ignored obvious things like dotfiles not coming up in a filepath.Glob("*") match on *nix systems.

Finally was able to switch back, so this has been tested thoroughly on linux. 

Draft/Edit: Handling edgecase

### CODE REVIEW

**Comment by schollz** [comment]
Thanks!! Simpler is always better. Give me some time to check out the PR, feel free to ping me if I forget!

**Comment by PThorpe92** [comment]
Yeah I found an input case I didn't handle anyway so I'll ping you for review when I get it figured out.

**Comment by PThorpe92** [comment]
I would like your opinion about the implementation of this feature, because this ultimately comes down to preference. Do you want it to ignore ALL files in the CWD that match your .gitignore? This seems like an obvious answer, however if you have a folder in your WD that is on your .gitignore list in that directory, and you try to send just that specific folder via croc, that would mean it would essentially skip it and send nothing. Or just parse the folders themselves to see if they are .git modules, then walk the sub dir and ignore those files?
currently if you "croc send *" or send anything in the cwd it will parse the top level and send only files that don't match.

**Comment by PThorpe92** [comment]
@schollz  This is all set when you have time to review.

sending source folder
```
$ ./croc send ../croc
Sending 151 files and 97 folders (26.2 MB)

$ ./croc send -all ../croc                                                       
Sending 154 files and 97 folders (37.1 MB)
```

**Comment by schollz** [comment]
All looks good! I would just request one thing - to make the default behavior the same as it is currently and use the flag to send only non-gitignore files.

**Comment by PThorpe92** [comment]
Do you have a preference as to what the flag should be called?

**Comment by PThorpe92** [comment]
@schollz  just came across this again because I saw croc on hackernews :) so I got rid of the hideous commit history. This should be all set (finally :+1: )

**Comment by schollz** [comment]
Ah great! Thanks for pinging me about it - it had left my radar (whoops!).

All looks fantastic, great work.

**Pull request merged**
