### PR TITLE
Bug Fix: Fixed error when sending files to a target directory that didn't exist

### PR DESCRIPTION
**Pull request by sk25469**
- Fixes [Issue #809](https://github.com/schollz/croc/issues/809), which caused errors when attempting to send files or folders located on a different drive letter on Windows systems.

### CODE REVIEW

**Comment by schollz** [comment]
does this fix #809? i'm pretty sure #809 can happen even if the `out` flag is not used

**Comment by sk25469** [comment]
Sure thanks for letting me know.
I will look for other ways, but can you help here with what other cases it might fail in? We can send to a specific directory only with the `--out` flag, right?

**Comment by schollz** [comment]
@ymich9963 can provide guidance

**Comment by ymich9963** [comment]
Sure I'll try to run it on the same machines and let you know what happens. Do I just use a flag to specify the output or does it get saved in the pwd?

**Comment by ymich9963** [comment]
I don't remember. I don't think I specified. I was just on the E:/ drive in one PC and on the C:/ drive in another. Could you specify the output for croc before I raised the issue? I remember that it would just output to the same directory as the source.

**Comment by ymich9963** [comment]
Should I build from source to test this?

**Comment by sk25469** [comment]
Yes u should build from source.
Earlier if u used `--out` and the folder didnt exist, it would just fail.
If u used without the flag, it would just send in the pwd

**Pull request closed without merging**
