### PR TITLE
pass through gofumpt

### PR DESCRIPTION
**Pull request by taigrr**
All code passed through gofumpt and retested. Should maintain versioned compatibility, as no public methods, variables or constants were renamed.

### CODE REVIEW

**Comment by taigrr** [comment]
Failure is due to go 1.18's lack of support for generics, which an updated dependency (uniseg) introduces. Attempted to update it in the PR to see if that would update the workflow, but apparently only the workflow yaml on the main branch is used (which makes sense from a security perspective).

I've reverted the workflow change. Will send a separate PR for that.

**Comment by taigrr** [comment]
Depends on #515

**Comment by schollz** [comment]
For some reason this is failing tests....

**Comment by taigrr** [comment]
Closing to replace with a better PR on this.

**Pull request closed without merging**
