### PR TITLE
fix(cli): make 'code too short' error symmetric on both sender and receiver side

### PR DESCRIPTION
**Pull request by nikoksr**
Hi @schollz,

This PR is to fix the bug described in #296.

### Proposed changes:

- Fix missing error on server side when a given code is too short
- In case of an error we now write into _stderr_ and return an _exit code 1_ instead of writing into _stdout_ and returning _exit code 0_

### CODE REVIEW

**Comment by schollz** [comment]
Thanks!

This didn't seem to fix this problem though:

> % croc send -c faa -t foobar
> %
> and the program just exits without telling me anything.

**Comment by nikoksr** [comment]
Hm, that's weird.

Output for me:
```sh
go run ./main.go send -c faa -t foobar
2021/02/01 16:05:28 code is too short
exit status 1
```

<br />

**Go version:** _go version go1.15.7 linux/amd64_

**Comment by schollz** [comment]
Hm it is weird. Here's what I get:

```
% git status
On branch nikoksr-fix/missing-code-too-short-error
nothing to commit, working tree clean
% go run ./main.go send -c faa -t foobar
% 
```

**Comment by nikoksr** [comment]
@schollz I just setup a fresh vm with Arch Linux installed on it, cloned this branch, ran the test command and got the expected output.

```go
go run ./main.go send -c faa -t foobar
2021/02/02 09:55:58 code is too short
exit status 1
```

**Comment by schollz** [comment]
Yeah no idea what happened but now its working for me! Thanks

**Comment by nikoksr** [comment]
Super weird lol Happy to help! Thanks for the great tool

**Pull request merged**
