### PR TITLE
added throttle upload feature

### PR DESCRIPTION
**Pull request by mbattista**
I added an upload throttler which was requested by https://github.com/schollz/croc/issues/429 .

If there are any mistakes in the code or points that can be improved I will try to fix them.

### CODE REVIEW

**Comment by mbattista** [comment]
The failing test is an result of `src/croc/croc_test.go` and `src/tcp/tcp_test.go` using port `8281`.

Running only `tcp_test.go` or changing the port to e.g. ´8291´ will result in a success.
This is the same error as the one from the master branch. Should I change the port in this PR?

Or is changing the port the wrong approach and the port should be freed after the`croc_test.go`?

**Comment by schollz** [comment]
Thanks no problem, this looks great!

**Comment by smitty1183** [comment]
I sure this is something really simple that I am missing but no matter how I phrase it every time I use --throttleupload it returns 'flag provided but not defined: -throttleupload"

**Comment by schollz** [comment]
The flag is throttleUpload , case sensitive

**Comment by smitty1183** [comment]
I am sorry I was using it that way just typed it here wrong but apparently it was the order in which I was using the flag, once I put it before send and the --code flag it worked perfectly

This is how I was trying it originally

croc send --code secret -throttleUpload 2000k C:\Backups\

Once I used it like this it started working

croc --throttleUpload 2000k send --code secret C:\Backups\

I thought the whole time I was defined the value wrong.

**Comment by raimocom** [comment]
. .  fell for that trap myself right now. This is not clearly communicated via `croc --help`

Expected behaviour is `croc COMMAND [OPTIONS] [FILENAME/FOLDER]`

**Comment by schollz** [comment]
@raimocom if this:

```
> croc --help 

...
GLOBAL OPTIONS:
...
   --throttleUpload value  Throttle the upload speed e.g. 500k
..
```

is not clear, please submit a PR to make it more clear.

**Comment by raimocom** [comment]
https://github.com/schollz/croc/pull/731

I guess i also intuitively expected --throttleUpload to be a command option of the send command. Is there any reason why it is a global option?

**Pull request merged**
