### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rain-1**
remove curl | bash recommendation

### CODE REVIEW

**Comment by schollz** [comment]
Thanks.

Is piping to bash from a https website any worse than installing a binary via `brew`/`scoop`? If so, do propose having installing from source to be the first option?

**Comment by Fastidious** [comment]
I don't see the problem with the pipe to bash, but there is a [releases](https://github.com/schollz/croc/releases) page with most common platforms. Use that instead?

**Comment by schollz** [comment]
What is the difference between downloading a release and piping to bash?

**Comment by Fastidious** [comment]
@schollz some will argue that pipe to bash might do more that just installing a binary, without running it, specially if run as root. As I said, I don't see a problem.

**Comment by jungle-boogie** [comment]
I support this PR in that it will silence the folks who have issues with piping to bash.

**Pull request merged**
