### PR TITLE
Package as a snap (https://snapcraft.io/)

### PR DESCRIPTION
**Pull request by jadolg**
Snaps are very convenient for software distribution.
It'll make it even easier to install and update `croc` on systems that already use snaps like Ubuntu.

After merging this branch, sign up at https://snapcraft.io/ and link the project and GitHub repository.
Snapcraft takes care of builds and edge releases. Only stable releases need some manual interaction.

Thank you very much for this great application :-)

### CODE REVIEW

**Comment by schollz** [comment]
snap is problematic see https://github.com/schollz/croc/issues/275 and https://github.com/schollz/croc/issues/190

I'm not interested in fielding any questions related to snap so I would only accept this if you or someone else volunteers to field all future snap related issues (basically maintain the croc as a snap)

**Comment by jadolg** [comment]
Ok, I'm in 🙂

**Comment by schollz** [comment]
Okay cool! I believe that the goreleaser also might need a change to add to snap- can you check on that for this PR? I have the snap credentials still and I think I can re add it

**Comment by jadolg** [comment]
I was wandering around and realized the previous confinement was `strict` with some plugs to have access to `home`. I checked the conditions to use `classic` confinement and we'll never get it. Half of the snap-related issues will be related to confinement. Now I see why you decided to go away from it. I'll close this.

**Comment by schollz** [comment]
Appreciate you looking into it!

**Pull request closed without merging**
