### PR TITLE
Added file/folder transfer time

### PR DESCRIPTION
**Pull request by El-JojA**
Okay, so now I tried to fix the issue #47 . Let me know what you think. Hope it helps :)

### CODE REVIEW

**Comment by afotescu** [comment]
Hey, if you don't mind I guess it would be better to put this lines of code
[411](https://github.com/schollz/croc/pull/49/files#diff-633296a45409f51865cca8ff2394d7fcR411)
and [412](https://github.com/schollz/croc/pull/49/files#diff-633296a45409f51865cca8ff2394d7fcR412)

outside if else statement to avoid duplicating this code, because you write this stuff anyway ;)

**Comment by El-JojA** [comment]
Hey @afotescu, you are totally right, thank you. I just learned a bit of go, travis-ci and screwing with PRs 😆

**Comment by afotescu** [comment]
@El-JojA cool, looks great !

**Comment by schollz** [comment]
Looks good, thanks @El-JojA @afotescu. Fixes #47

**Comment by El-JojA** [comment]
Thank you guys!

**Pull request merged**
