### PR TITLE
update clone url

### PR DESCRIPTION
**Pull request by jungle-boogie**
Unless I'm doing something wrong, /v6 isn't needed:
```
$ go get -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/local/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/jungleboogie/gopath/src/github.com/schollz/croc/v6 (from $GOPATH)
```

### CODE REVIEW

**Comment by schollz** [comment]
You should have `GO111MODULE=on` before running `go get`. The readme should be updated with that because this is a common problem...

**Comment by jungle-boogie** [comment]
```
$ GO111MODULE=on
$ go get -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/local/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/jungleboogie/gopath/src/github.com/schollz/croc/v6 (from $GOPATH)
```

**Comment by schollz** [comment]
That is weird.

I can replicate your error, but only with GO111MODULE off.

```
$ cd 
$ GO111MODULE=off go get -u -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/local/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/zns/go/src/github.com/schollz/croc/v6 (from $GOPATH)
```

when I turn it on, it works fine


```
$ GO111MODULE=on go get -u -v github.com/schollz/croc/v6
Fetching https://golang.org/x/sys?go-get=1
Fetching https://golang.org/x/crypto?go-get=1
Fetching https://golang.org/x/text?go-get=1
Fetching https://golang.org/x/tools?go-get=1
...
```

Which Go version are you using?


```

**Comment by jungle-boogie** [comment]
I am using
```
$ go version   
go version go1.12.7 openbsd/amd64
```
Ah, when I have `GO111MODULE=on go get -u -v github.com/schollz/croc/v6`, it performs the download...

```
$ GO111MODULE=on go get -u -v github.com/schollz/croc/v6
go: finding github.com/schollz/croc/v6 v6.0.12
go: finding github.com/schollz/logger v1.0.1
Fetching https://golang.org/x/sys?go-get=1
go: finding github.com/spaolacci/murmur3 v1.1.0
go: finding github.com/schollz/mnemonicode v1.0.1
go: finding github.com/urfave/cli v1.20.0
go: finding github.com/mattn/go-colorable v0.1.2
go: finding github.com/schollz/pake v1.1.1
go: finding github.com/schollz/peerdiscovery v1.4.0
```

**Comment by schollz** [comment]
@jungle-boogie Is this another OpenBSD thing? Like do you need to do `export GO111MODULE=on` for the bash to hold the variable?

In Ubuntu I can do either-  I can toggle it like you tried to do, just fine:

```
$ GO111MODULE=off
$ go get -u -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/local/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/zns/go/src/github.com/schollz/croc/v6 (from $GOPATH)
$ GO111MODULE=on
$ go get -u -v github.com/schollz/croc/v6
Fetching https://gopkg.in/tylerb/is.v1?go-get=1
Fetching https://golang.org/x/net?go-get=1
Fetching https://golang.org/x/crypto?go-get=1
....
```

**Comment by jungle-boogie** [comment]
Not exactly sure what's happening...
```
$ GO111MODULE=on
$ go get -u -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/local/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/jungleboogie/gopath/src/github.com/schollz/croc/v6 (from $GOPATH)
$ echo $GO111MODULE
on
```

**Comment by schollz** [comment]
That is super weird. I wonder if Go is having trouble getting the environmental variables in OpenBSD? I have no idea.

**Comment by jungle-boogie** [comment]
hi @schollz,

If you would like to test it (and the rest of your project), you can sign up for a free shell account here:
https://tilde.institute/

That service is running OpenBSD 6.4 -release, which is from October 2018:
https://www.openbsd.org/64.html

Otherwise, is there any harm in having the whole gomodule thing on one line?

**Comment by ferebee** [comment]
I find that on SmartOS, using a native SmartOS zone with image base-64 19.2.0 and go 1.12.5 installed from pkgsrc, I see the same errors quoted above, whether or not I set `GO111MODULE=on` first.

It works if I run

`# go get -u -v github.com/schollz/croc`

**Comment by bobberb** [comment]
Same issues on Arch.

I did a simple go get -u -v github.com/schollz/croc as well, built without issue

**Comment by Fumesover** [comment]
Just got the same issue, it's just a bash variable issue:
```bash
$ # No variable set
$ go get -u -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/lib/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/fumesover/go/src/github.com/schollz/croc/v6 (from $GOPATH)

$ # Will not work if this is a bash-only variable
$ GO111MODULE=on                         
$ go get -u -v github.com/schollz/croc/v6
github.com/schollz/croc (download)
package github.com/schollz/croc/v6: cannot find package "github.com/schollz/croc/v6" in any of:
        /usr/lib/go/src/github.com/schollz/croc/v6 (from $GOROOT)
        /home/fumesover/go/src/github.com/schollz/croc/v6 (from $GOPATH)

$ # Works if passed to the env of the command
$ GO111MODULE=on go get -u -v github.com/schollz/croc/v6
go: github.com/schollz/croc/v6 upgrade => v6.4.11
go: downloading github.com/schollz/spinner v0.0.0-20180925172146-6bbc5f7804f9
[...]

$ # Also works if you exports it
$ export GO111MODULE=on                  
$ go get -u -v github.com/schollz/croc/v6
go: downloading github.com/schollz/croc v1.0.0
go: downloading github.com/schollz/croc/v6 v6.4.11
go: downloading github.com/schollz/croc v3.0.6+incompatible
[...]
```

**Pull request closed without merging**
