### PR TITLE
Add printing receive command as a qr code with new --qrcode flag

### PR DESCRIPTION
**Pull request by lukenvn**
Hi guys, 

This pull request adds a new feature to the Croc software, allowing users to display the receive command as a QR code by using the --qrcode flag. This feature enhances the usability and convenience of Croc by providing an easily scannable QR code representation of the receive command.I also plan to add scan qrcode feature in croc android soon.

Changes Made:
1. Added a new command-line flag --qrcode to the Croc software.
2. When the --qrcode flag is used, the receive command is extracted and converted into a QR code using the go-qrcode library.
3. The QR code is displayed to the user in the command-line interface.
image

Benefits:
1. Improved user experience: Users can now conveniently display the receive command as a QR code, making it easier to scan and share.
2. Enhanced accessibility: The QR code representation allows users to use QR code scanning applications or libraries to automate the process of capturing the receive command.
3. Increased efficiency: By providing a direct QR code display option, users can quickly access the receive command without manually typing or copying it.

P/s: This is my first time of using go lang so Im not sure what i'm is in good practice, so please let me know if i should improve something. Thank you in advanced .

### CODE REVIEW

**Comment by schollz** [comment]
thanks for the contribution!

how do you use this feature? do you receive things are your phone?

code looks great.

**Comment by lukenvn** [comment]
> thanks for the contribution!
> 
> how do you use this feature? do you receive things are your phone?
> 
> code looks great.

Sorry for my late response. Ya on the phone I will use the qr scanner to get the code, then paste it to the crocgui recevie tab, just simple like that.

**Comment by schollz** [comment]
@jpph conflicts need to be resolved. go ahead and rebase this yourself, or checkout the commits themselves (not too many lines) and create a new pr with it.

**Comment by jpph** [comment]
Sorry I do not have the knowledge and capabilities to do so... if too much work you can leave it closed... Thank you :-)

**Comment by Ozoniuss** [comment]
https://github.com/schollz/croc/pull/847

**Pull request closed without merging**
